### ISSUE TITLE
Extra marker appears on map

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/charts#1]
- Create map
- Add markers with caption
- Add action "redraw map"
- Start app
- Click marker
- invoke "redraw map"
```
 private void redraw() {
        map.clearMarkers();
        ...
}
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-4986

**Comment by Flaurite** [comment]
Can't reproduce in 6.10, 7.0+
