### ISSUE TITLE
Method for close infowindow is not working

### ISSUE THREAD

**Issue by Saeron** [cuba-platform/charts#107]
I am usgin this method to remove the previus popup, so I just have one popu at the same time, but is not closing and still showing in the map. So closeInfoWindow is not closing the popup.
```
map.addMarkerClickListener(e-> {
            Marker marker = e.getMarker();
            if(w!=null && map.isInfoWindowOpen(w)){
                map.closeInfoWindow(w);
            }
            w = map.createInfoWindow(marker.getCaption(), marker);
            map.openInfoWindow(w);
        });
```
I am using last version of cuba and I install the addon from the market.

**Comment by skatova** [comment]
This problem is reproduced. 
See attached project
[testmap.zip](https://github.com/cuba-platform/charts/files/5597692/testmap.zip)

**Comment by Saeron** [comment]
I am getting this warning in the browser:
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

So it migth be because the google api.
