### ISSUE TITLE
Provide an easy way to customize date format for REST API

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/charts#17]
At the moment the only way to do it is to override the whole datatypes.xml file.
OR
Probably it will be enough just to have timezone information in he default datetime format.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9674

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba #904](https://github.com/cuba-platform/cuba/issues/904) via [**ZenHub**](https://www.zenhub.com/)
