### ISSUE TITLE
Implement renderingDelay attribute for AmCharts rendering delay

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/charts#21]
====*Changes*====

All charts have *renderingDelay* attribute except *stockChart*;

renderingDelay - sets rendering delay in which the chart should be rendered (renders instantly if not set). The delay is time in ms.
[AmCharts doc link|https://docs.amcharts.com/3/javascriptcharts/AmCharts#makeChart]

Usage exmaple:
XML
```
<chart:pieChart id="pieChart"
                renderingDelay="1000.25">
```

Java
```
pieChart.setRenderingDelay(1000.25); // takes Double value;
pieChart.getRenderingDelay();
```

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-9969", "causes:": "https://youtrack.haulmont.com/issue/PL-10539"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-10294

**Comment by Flaurite** [comment]
Unnecessary feature, animation has already fixed in [PL-9969](https://youtrack.cuba-platform.com/issue/PL-10294)
