### ISSUE TITLE
Create an "Analyze" action to upload selected table records to Pivot

### ISSUE THREAD

**Issue by glaschenko** [cuba-platform/charts#27]
See Warlord implementation for details (by @tinhol )  

----
### Changes
Using new Action - `ShowPivotAction` you can export data from components that extends `ListComponent` class to the `PivotTable` component.

#### Description
ShowPivotAction has several modes for export:  all rows and selected rows. You don't have to select it, because it depends on selected rows.

All rows will be exported by default without confirmation dialog if you didn't select rows.
A confirmation dialog will be shown If you select some rows and click on a button with action:
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/3e998f23-9cee-4092-a939-a48074e71a3a)

The `PivotTable` component will be shown in a new tab with `editable = true` by default.

In the opened tab, `PivotTable` has an extension that allows you to export pivot data to excel (if the current renderer is supported).

**Note**, if property has any type from following list:
1) collection type;
2) byte array
3) uuid
or has system level annotation, or doesn't have security access for view, it will be ignored.

#### API
To create action, you should send component that extends `ListComponent` class as a parameter. Also, you can send an action id otherwise default id will be used.
```
ShowPivotAction action = ShowPivotAction.create(table);
//or
ShowPivotAction action = ShowPivotAction.create(table, "actionId");
```
By default `ShowPivotAction` send all properties that defined in the `View` of `CollectionDatasource`. If you want to send certain properties or exclude, you can use the following methods:
```
withIncludedProperties() // received List<String> of properties name;
withExcludedProperties() // received List<String> of properties name;
```
As `ShowPivotAction` has a fluent API, you can use following code entry:
```
ShowPivotAction action = ShowPivotAction.create(table)
        .withIncludedProperties(Arrays.asList("login", "name", "active", "group", "position"))
        .withExcludedProperties(Arrays.asList("name", "position"));
```
**The order** of methods doesn't matter:
In the above example, the result of applied properties is: ("login", "active", "group")
If we change the order of invoked methods:
```
ShowPivotAction action = ShowPivotAction.create(table)
        .withExcludedProperties(Arrays.asList("name", "position"))
        .withIncludedProperties(Arrays.asList("login", "name", "active", "group", "position"));
```
The result of applied properties will be: ("login", "active", "group").
**All incorrect properties are ignored.**

To configure pivot table, you must use the following method:
```
withNativeJson() // received String json;
```
JSON structure for a non-editable pivot table:
```
{
	"cols": ["localized property", "localized property"],
	"rows": ["localized property"],
	"editable": false,
	"renderer": "heatmap",
	"aggregation": {
		"id": "d8fc3fdf-730d-c94f-a0c8-72a9ce3dcb3a",
		"mode": "sumOverSum",
		"properties": ["localized property", "localized property"]
	}
}
```
JSON structure for editable pivot table:
```
{
	"cols": ["localized property"],
	"rows": ["localized property"],
	"editable": true,
	"renderers": {
		"selectedRenderer": "barChart"
	},
	"autoSortUnusedProperties": true,
	"aggregationProperties": ["localized property", "localized property"],
	"aggregations": {
		"selectedAggregation": "count",
		"aggregations": [{
			"id": "647780f0-c6d0-6ade-a63a-542b5c8cdbd5",
			"mode": "count",
			"caption": "Count"
		}, {
			"id": "c2663238-2654-67f0-2dec-add6962d867c",
			"mode": "sumOverSum"
		}]
	}
}
```
For more information about configuration properties see https://github.com/nicolaskruchten/pivottable/wiki/Parameters

#### For QA
For non-persistent Entity (e.g. TipInfo)
  Without and with view:
a) without "include" and "exclude" properties - should show all available properties
b) using `withIncludedProperties()` - should show only included
c) using `withExcludedProperties()` - should show available properties minus excluded
d) using both methods - excluded properties will be applied to included. If count of result properties is zero - all available properties will be shown.

For peristent Entity (e.g. User)
 Without and with view
a - d) same steps
e) Check security for properties
f) Check uuid property
g) Check byte array property
h) Try to use in `withIncludedProperties()` propertyPath (e.g. group.name)

**Comment by glaschenko** [comment]
Similar to TablePrintFormAction

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[7b275f10](https://git.haulmont.com/platform/charts/commit/7b275f10d306707fe70db38e277f213be1c46be3) in **release_6_10** - Create an "Analyze" action to upload selected table records to Pivot #27

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[1f662ece](https://git.haulmont.com/platform/charts/commit/1f662ecec0141d12b0446fe01dfc04dce395568c) in **master** - Create an "Analyze" action to upload selected table records to Pivot #27

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[d7b86c71](https://git.haulmont.com/platform/charts/commit/d7b86c7102b42e17bfac87d5677f71e826d12795) in **master** - Create an "Analyze" action to upload selected table records to Pivot #27

Replaced ShowPivotAction to com.haulmont.charts.web.gui

**Comment by natfirst** [comment]
If the pivot table does not have any attributes and the datasource does not have the view, use the _local or _minimal view of the entity to set up the table.

Also, fix the java docs for the methods, add more information.

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[718d4987](https://git.haulmont.com/platform/charts/commit/718d498744ff18a7094afdbe4bcc1c727932bc08) in **release_6_10** - Create an "Analyze" action to upload selected table records to Pivot #27

Fixed propertiesPaths, added caption to pivot-table-screen;
Changed javaDoc, fixed getting properties from view, filtering
properties, order of invoked fluent methods doesn't matter

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[e8008ab5](https://git.haulmont.com/platform/charts/commit/e8008ab5b81c63b525d22af13603f9a24cd88081) in **master** - Create an "Analyze" action to upload selected table records to Pivot #27

Fixed propertiesPaths, added caption to pivot-table-screen;
Changed javaDoc, fixed getting properties from view, filtering
properties, order of invoked fluent methods doesn't matter

**Comment by natfirst** [comment]
using both methods - excluded properties will be applied to included. If the count of result properties is zero nothing should be shown

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[e6edd6ef](https://git.haulmont.com/platform/charts/commit/e6edd6efbb6fdaee6c61917b79e64820304ff666) in **release_6_10** - Create an "Analyze" action to upload selected table records to Pivot #27

Use certain MetaClass for metaProperty

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[c1f0c1da](https://git.haulmont.com/platform/charts/commit/c1f0c1da6e1accbe28e09aefe9dc8016b5b7ce73) in **master** - Create an "Analyze" action to upload selected table records to Pivot #27

Use certain MetaClass for metaProperty
