### ISSUE TITLE
Use standard Gradle compileOnly configuration instead of provided

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/charts#37]
Related to cuba-platform/cuba-gradle-plugin#27

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[f2c6a387](https://git.haulmont.com/platform/charts/commit/f2c6a387fc8aa8849735aa714a5985a11c35aeb5) in **master** - Use standard Gradle compileOnly configuration instead of provided #37
