### ISSUE TITLE
PivotTable does not refresh UI on editable change

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/charts#41]
### Environment

- Platform version: 6.9.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

1. Try to change editable of PivotTable on click

```
public class ClientBrowse extends AbstractLookup {
    @Inject
    private PivotTable clientPivotTable;

    public void switchMe() {
        clientPivotTable.setEditable(!clientPivotTable.isEditable());
    }
}
```

- Expected behavior

UI should change between editable and readonly representation.

- Actual behavior

UI is changed only if we use F5 key and refresh the page

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[afa68e41](https://git.haulmont.com/platform/charts/commit/afa68e416ff00020b1092b2845b6fabad96d87d4) in **release_6_9** - PivotTable does not refresh UI on editable change #41

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[ef6eecb8](https://git.haulmont.com/platform/charts/commit/ef6eecb88500fe47f9b83730749dced7d3b3122c) in **release_6_10** - PivotTable does not refresh UI on editable change #41

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[7ffa797d](https://git.haulmont.com/platform/charts/commit/7ffa797dd1046672a6dd8c815bb39e8f37abf7b4) in **master** - PivotTable does not refresh UI on editable change #41

**Comment by jreznot** [comment]
Demo project: [pivot-refresh.zip](https://github.com/cuba-platform/charts/files/2303032/pivot-refresh.zip)
