### ISSUE TITLE
PivotTable does not set aggregation and renderers in editable mode

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/charts#44]
### Environment

- Platform version: 6.9.5
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

1. Define `pivotTable`
```
<chart:pivotTable id="pivotTable"
                  datasource="clientsPivotDs"
                  height="300px"
                  width="100%">
    <chart:properties>
        <chart:property name="title"/>
        <chart:property name="rank"/>
        <chart:property name="money"/>
    </chart:properties>
</chart:pivotTable>
```
3. Set editable by default:
```
public class ClientBrowse extends AbstractLookup {
    @Inject
    private PivotTable pivotTable;

    @Override
    public void ready() {
        super.ready();

        pivotTable.setEditable(true);
    }
```

3. On button click we want to apply specific renderer and aggregation:
```
public void onTestBtnClick() {
    pivotTable.setEditable(true);
    pivotTable.setRows(Collections.singletonList("money"));
    pivotTable.setColumns(Collections.singletonList("rank"));
    pivotTable.setAggregationProperties(Collections.singletonList("money"));

    pivotTable.setRenderers(new Renderers());
    pivotTable.getRenderers().setDefaultRenderer(Renderer.TABLE);

    pivotTable.setAggregations(new Aggregations());
    pivotTable.getAggregations().setDefaultAggregation(AggregationMode.SUM);
    pivotTable.repaint();
}
```

4. Open screen and click on `Switch Pivot` button

Strange thing happens: we receive `RefreshEvent` from client side with incorrect aggregation and renderers back to server side after button click.

Demo project: 
[https://app.zenhub.com/files/131167043/98b13cdf-cc27-4600-93d8-33fdfb3941fb/download](https://app.zenhub.com/files/131167043/98b13cdf-cc27-4600-93d8-33fdfb3941fb/download)

- Expected behavior

Settings applied, renderer and aggregation is set after click

- Actual behavior

Settings are not applied on button click

**Comment by haulmont-git** [comment]
Git changesets by `gorelov`: 

[e025624f](https://git.haulmont.com/platform/charts/commit/e025624fb09f670c126dfacee8a4e6ef0bb3ba36) in **release_6_9** - PivotTable does not set aggregation and renderers in editable mode #44

**Comment by haulmont-git** [comment]
Git changesets by `gorelov`: 

[33a40d3e](https://git.haulmont.com/platform/charts/commit/33a40d3e16d2725fe382c149e8d8a540fe007306) in **release_6_10** - PivotTable does not set aggregation and renderers in editable mode #44

**Comment by haulmont-git** [comment]
Git changesets by `gorelov`: 

[2a2be62b](https://git.haulmont.com/platform/charts/commit/2a2be62b4bde9f8f25327045668b9079a8997c9f) in **master** - PivotTable does not set aggregation and renderers in editable mode #44
