### ISSUE TITLE
Pivot table filter box does not disappear after clicking outside of it

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/charts#46]
1) Create the editable pivot table
2) pvtFilterBox does not disappear in case of clicking outside himself

![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/10780231-3af8-4057-b5a3-141b299fd84f)

It would be great if this box will disappear after clicking outside the box, for now every drop-down list disappears after clicking outside it.

**Comment by glebfox** [comment]
This is the default behavior of `pivottable js`. We won't alter the original js library. Instead, you can create an issue in the authors' repository: https://github.com/nicolaskruchten/pivottable.
