### ISSUE TITLE
Update PivotTable to v2.21.0

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#47]
Added: 

* Use `barmode: 'relative'` for best Plotly bar-stacking behaviour
* `showUI` parameter in `pivotUI()` to hide UI and paper over differences between `pivot()` and `pivotUI()`
* `rowTotals` and `colTotals` options for table renderers
---
### Changes
New properties:
- `showRowTotals` - options for row with total values (true by default);
- `showColTotals` - options for column with total values (true by default);
- `showUI` - it can be used only with editable `PivotTable` and can hide or show UI elementes (true by default).

`showRowTotals` and `showColTotals` properties work only with table-renderers (heatmap, table, etc).

### Examples
- XML:
```
...
<chart:pivotTable id="tipsPivotTable"
                  datasource="tipsDs"
                  showRowTotals="false"
                  showColTotals="false"
                  renderer="HEATMAP">
...
<chart:pivotTable id="tipsPivotTableUI"
                  showUI="false"
                  datasource="tipsDs"
                  editable="true">
...
```
- Java:
```
tipsPivotTable.setShowColTotals(false);
tipsPivotTable.isColTotalsShown();
        
tipsPivotTable.setShowRowTotals(false);
tipsPivotTable.isRowTotalsShown();

tipsPivotTableUI.setShowUI(false);
tipsPivotTableUI.isShowUI();
```
- Native JSON for show col and row totals:
```
{
   "rendererOptions": {
      "table": {
         "rowTotals": false,
         "colTotals": false
      }
   }
}
```
- Native JSON for showUI property:
```
{
   "showUI": false
}
```
### QA
- check properties from XML layout
- check properties from Java API
- check native JSON;

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[87d60aa7](https://git.haulmont.com/platform/charts/commit/87d60aa763a4b0e12fdcb4415ec13c2cbddcbb50) in **release_6_10** - Update PivotTable to v2.21.0 #47

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[8ede5be5](https://git.haulmont.com/platform/charts/commit/8ede5be591fdc8a82a88b886e9613ac14c51b3ef) in **master** - Update PivotTable to v2.21.0 #47

**Comment by natfirst** [comment]
New attributes are not loaded from the xml layout

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[22466cc3](https://git.haulmont.com/platform/charts/commit/22466cc30fe40dc88e38f058ebadf5375a6b6eab) in **release_6_10** - Update PivotTable to v2.21.0 #47

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[5f035d3d](https://git.haulmont.com/platform/charts/commit/5f035d3d6d4e36a7c7eda53ba43d3b0d3f27f5ab) in **master** - Update PivotTable to v2.21.0 #47

**Comment by natfirst** [comment]
Client-side exception occurs when trying to open Pivot screen.
Error sending state change events

com.google.gwt.event.shared.UmbrellaException: Exception caught: (SyntaxError) : Unexpected token .

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/eea8f5c6-275b-48f9-bff6-71b34de1c46e)

**Comment by Flaurite** [comment]
It is bug of messagePack in screen. See issue: cuba-platform/cuba#1306
