### ISSUE TITLE
Add date format to PivotTableExtension

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/charts#48]
Add date format property for serialization and deserialization of Date object.

The main idea is to provide `dateFormat` property to show formatted date in the `PivotTable` cells.
For instance:

`dateFormat="yyyy-MM-dd"`
date in the cell: 2019-01-01

It would allow us to detect date property from the client side and handle it in the `PivotExcelExporter`. So in the generated excel file, we will set "date format" style to cells with Date.

---
### Changes

PivotTableExtension now available detect dateTime, date and time types and set corresponding format in the excel file. By default it does not detect given types.

In order to export with corresponding type it is necessary to set specific parsing format using the following methods:
```
setDateTimeParseFormat(String) // DateTime
setDateParseFormat(String) // Date
setTimeParseFormat(String) // Time
```
It will be applied for all dateTime, date, time properties in the PivotTable.

#### How to use
```(Java)
@Inject
private PivotTable pivotTable;
private PivotTableExtension extension;

@Subscribe
private void onInit(InitEvent event) {
    extension = new WebPivotTableExtension(pivotTable);
    extension.setDateTimeParseFormat("dd/MM/yyyy HH:mm");
    extension.setDateParseFormat("dd/MM/yyyy");
    extension.setTimeParseFormat("HH:mm");
}
```

Another little improvement is automatic resizing column width according to the length of content in the widest cell in column. 

![image](https://user-images.githubusercontent.com/22093943/60667010-85879f00-9e79-11e9-977a-23947ff662a4.png)

### How test
1. Try DateTime, Date, Time datatypes and their defaults formats; In the excel cell can have types:: custom, time and date;
2. In the output file make sure that columns are resized to the widest cell in column.

**Comment by jreznot** [comment]
What should be done ?

**Comment by glebfox** [comment]
The same question.
