### ISSUE TITLE
Pack widgetsets to JAR files

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/charts#49]
### QA

Check that charts still correctly work

Make sure that the project can be successfully created and started and when it has a `web-toolkit` module, and when it does not have it.

---
Relates to cuba-platform/cuba#542

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[7f7c0255](https://git.haulmont.com/platform/charts/commit/7f7c0255e311c03d7a46c84579215051534795a5) in **master** - Pack widgetsets to JAR files #49

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[fdffd363](https://git.haulmont.com/platform/charts/commit/fdffd363f1addf9b91c4f08564c2945ca4a7c0d9) in **master** - Pack widgetsets to JAR files #49
