### ISSUE TITLE
Data binding with CollectionContainer

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/charts#52]
Provide ContainerDataProvider and deprecate setDatasource() method.
Also, charts should provide `dataContainer` XML attribute in XSD  

---
### Changes
All charts, stock charts and pivot table elements support new property:
```
dataContainer
```
It takes `CollectionContainer` as data source. For this `CollectionContainer` is created new DataProvider:
```
ContainerDataProvider
```
Old property `datasource` and `EntityDataProvider` are **deprecated**.

**Important**
Now If you want to set programmaticaly `CollectionConatiner` you should use `setDataProvider(DataProvider)`.
```
ContainerDataProvider dataProvider = new ContainerDataProvider(collectionContainer);
chart.setDataProvider(dataProvider);
```
From XML layout:
```
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
         xmlns:chart="http://schemas.haulmont.com/charts/charts.xsd"
         ... >
<data>
    <collection id="pieDs"
                class="com.haulmont.refapp.web.ui.charts.entity.CountryLitres"
                view="_local"/>
</data>
<chart:serialChart id="lineChart"
                   dataContainer="lineDs"
                  ...
                   width="100%"
                   height="100%">
                 ...
</chart:serialChart>
```
### For QA
1. Check all charts, stock charts, pivot and PivotTableExtension work with datasource
2. Check all with new CollectionConainter and ContainerDataProvider.

Patch for new features Refapp:
[charts_refapp_patch.zip](https://github.com/cuba-platform/charts/files/2459546/charts_refapp_patch.zip) (Don't be afraid of errors in XML)

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[9378c0a8](https://git.haulmont.com/platform/charts/commit/9378c0a8f6941088cbb9098ae79e3719e150fa15) in **master** - Data binding with CollectionContainer #52

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[e6eac892](https://git.haulmont.com/platform/charts/commit/e6eac89270ece11909240e255ea9219c2469a941) in **master** - Data binding with CollectionContainer (Typo in javaDoc, refactor) #52
