### ISSUE TITLE
Rework events with EventHub and Consumer<E>

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/charts#54]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

Use new events schema for Chart / Map / PivotTable

---
### Changes
All events use `EventHub` for subscribers.
"Add" methods has following structure:
```
Subscription addSomeListener(Consumer<SomeEvent> listener);
```
Event object extends `java.util.EventObject`. "Add" methods return Subscription if you want to remove listener in the future. 
"Remove" methods are deprecated, cause we should use:
```
subscription.remove();
```

Also, MapViewer handler takes `MapInitEvent` instead of parameters.

### For QA
There is no sense to check all events for every chart, so you can try following events:
1. For `SerialChart`
- GraphItemClickEvent. Try to get from event graph object. Can be null if there is no id is defined.
- GraphItemRightClickEvent. Try to get from event graph object. Can be null if there is no id is defined.
2. For `StockChart`
- StockGraphItemRightClickEvent. Try to get from event `StockPanel` and `StockGraph`. `StockGraph` can be null if there is no id in graph list.
- StockEventClickEvent. Try to get `StockGraph` from event. `StockGraph` can be null if there is no such id in graph list. Apply this pach to see events in screen: 
[stock_event_patch.zip](https://github.com/cuba-platform/charts/files/2483092/stock_event_patch.zip)

3. Also, try new API for subscriptions in old and new screens
For instance,
```
@Subscribe("pieChart")
public void onSlice(Chart.SliceClickEvent event) {
    notifications.create().setCaption(event.getAbsoluteX() + "").show();
}
```

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[1fc59656](https://git.haulmont.com/platform/charts/commit/1fc5965654d9a50b4993aa416716567c8d190957) in **master** - Rework events with EventHub and Consumer<E> #54
