### ISSUE TITLE
Revert event listeners for MapViewer as deprecated classes

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/charts#61]
### Environment
- Platform version: 7.0.0
- Client type: Web
### Description of the bug or enhancement
Revert event listeners for MapViewer and support them for compatibility.

### How to test
1. Create application with Charts
2. Add Map to the screen
3. And add:
```
map.addMapInitListener(new MapInitListener() {
    @Override
    public void init(GeoPoint center, int zoom, GeoPoint boundNE, GeoPoint boundSW) {
        showNotification("MapInitEvent");
    }
});

map.addMapClickListener(event -> {
    showNotification("MapClickEvent");
});
```
4. Try to migrate to 7.0. All events should work fine.

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[77d1ead0](https://git.haulmont.com/platform/charts/commit/77d1ead041ca195c4413f1f8e4b826b308778d40) in **master** - Revert event listeners for MapViewer as deprecated classes #61
