### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/charts#64]
com.haulmont.charts.gui.components.action.ShowPivotAction#getAdditinalProperties

Deprecate incorrect method, create new method with correct name.

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[ee2a1702](https://git.haulmont.com/platform/charts/commit/ee2a1702318e48269db2cab29660baca29ab56de) in **release_6_10** - Typo in method name #64

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[300035a2](https://git.haulmont.com/platform/charts/commit/300035a2a955fee121fb6351b1da84e0a05c59eb) in **master** - Typo in method name #64
