### ISSUE TITLE
Animation triggers every time the data is changed for PieChart

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#68]
### Environment

- Platform version: 6.10.4

### Description of the bug or enhancement

- Minimal reproducible example

[PieChart.zip](https://github.com/cuba-platform/charts/files/2610405/PieChart.zip)

- Expected behavior

Animation doesn't trigger after incremental update

- Actual behavior

![pie-chart](https://user-images.githubusercontent.com/6077149/48939770-cf48f800-ef2e-11e8-815b-a7c4ec0ec4de.gif)

Also, animation triggers every time the PieChart size has been changed.

----
### How to test
For Pie chart (7.0+).
1. Check incremental update in the refapp;
2. Apply the following patch: [animation_refapp_7_0.zip](https://github.com/cuba-platform/charts/files/3261856/animation_refapp_7_0.zip) and open _Tests -> Sample Prototype_.
Make sure that animation is triggered only once.

6.10
3. Check incremental update in the refapp
4. Download sample: [chartProblem.zip](https://github.com/cuba-platform/charts/files/3261874/chartProblem.zip) update it to 6.10
4.1 Download scenario for folders pane: [cuba-app-test-scenario.zip](https://github.com/cuba-platform/charts/files/3261893/cuba-app-test-scenario.zip)
4.2 Apply scenario for folder
4.3 Open _Application -> Test Entities_ and create some instances
4.4 Open _Application -> Screen -> second tab_ and make sure that animation is triggered only once. (wait 10 sec)

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[f6c78fd3](https://git.haulmont.com/platform/charts/commit/f6c78fd387e6a971fc9d662a0abc884eb8b64955) in **release_6_10** - Animation triggers every time the data is changed for PieChart #68
