### ISSUE TITLE
Replace SimpleDateFormat with FastDateFormat in chart data serialization

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#71]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Currently `SimpleDateFormat` is used to serialize dates in `ConfigDateSerializer` and its instance is created every time serialization is processed. 

Replace `SimpleDateFormat` with `FastDateFormat` that is thread-safe and can be extracted into `static final` field.

----

### For QA
Open in refapp StockCharts and Charts:
- [ ] Check that they work fine
- [ ] Check that dates have the correct format

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[cd76bc0a](https://git.haulmont.com/platform/charts/commit/cd76bc0aca1086b70f3abafc3c6280d1e3eb552a) in **master** - Replace SimpleDateFormat with FastDateFormat in chart data serialization #71
