### ISSUE TITLE
Update google map api version to v3.35

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/charts#73]
In version 3.28 we can see following message:
```
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```
And have bug with `InfowWindow`.

**Steps to reproduce:**
1) Open refapp -> Charts -> Map
2) Try to click on the marker

**ER**
Info window should be shown
**AR**
StackTrace:
```
TypeError: Cannot set property 'className' of null
    at vSk_g$.BTk_g$ [as setInfoWindowClass_0_g$] (GoogleMapWidget.java:1208)
    at jVk_g$.kVk_g$ [as onEvent_8_g$] (GoogleMapWidget.java:1165)
    at jVk_g$.lVk_g$ [as onEvent_0_g$] (GoogleMapWidget.java:1164)
```

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[f160a789](https://git.haulmont.com/platform/charts/commit/f160a789c799c0fbda955c632a04cd5c8f98c379) in **release_6_10** - Update google map api version to v3.35 #73
