### ISSUE TITLE
StockGraph 'periodValue' is serialized in lower case

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#76]
According to the [documentation](https://www.amcharts.com/docs/v3/reference/stockgraph/#periodValue_property) `periodValue` values starting with capital letters.

Fix `StockGraphValue` id values.

**Comment by haulmont-git** [comment]
Git changesets by `pribavkin`: 

[a9e5ed24](https://git.haulmont.com/platform/charts/commit/a9e5ed24371097dfba129d9e71b5976a3b4f5d8b) in **release_6_10** - StockGraph 'periodValue' is serialized in lower case #76
