### ISSUE TITLE
PieChart is not shown when starDuration = 0

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/charts#81]
### Environment
- Platform version: 6.10+
- Client type: web;

### Description of the bug or enhancement
It seems that JsUtils#getObjectByKey in charts works incorrectly.

- Minimal reproducible example
1. Create PieChart with `startDuration=0`
2. Open screen;

- Expected behavior
Pie chart is shown.
- Actual behavior
Nothing is shown.

Related forum post: [link](https://www.cuba-platform.ru/discuss/t/nekorrektnoe-otobrazhenie-piechart-s-otklyuchennoj-animacziej/3312)

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[611110b3](https://git.haulmont.com/platform/charts/commit/611110b3d8d06ea640eca12987dcfa810063b1ad) in **release_6_10** - PieChart is not shown when starDuration = 0 #81
