### ISSUE TITLE
Update google map api version to v3.38

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#82]
### Description of the bug or enhancement

In a browser console we can see the following warning:

```
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

Also, have a bug with InfowWindow.

**Steps to reproduce:**

1. Open refapp -> Charts -> Map
2. Try to click on the marker

ER

InfoWindow is displayed

AR

```
SEVERE: (TypeError) : Cannot set property 'className' of null
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot set property 'className' of null
```

<img width="207" alt="Screenshot 2019-08-22 at 16 24 44" src="https://user-images.githubusercontent.com/6077149/63514302-5eecf880-c4f9-11e9-8f75-d95b7b258114.png">

**Comment by haulmont-git** [comment]
Git changesets by `gorelov`: 

[e9232f7c](https://git.haulmont.com/platform/charts/commit/e9232f7ca12f4cc2b162460705f1b1fe2a1a21a2) in **release_6_10** - Update google map api version to v3.38 #82
