### ISSUE TITLE
Chart can overlap other component if CubaManagedTabSheet is used 

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#84]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement

- Minimal reproducible example

[jstest.zip](https://github.com/cuba-platform/charts/files/3546319/jstest.zip)

1. Open entity browser
2. Open Chart screen
3. Switch to the previously opened entity browser

- Actual behavior

<img width="792" alt="Screenshot 2019-08-27 at 17 28 36" src="https://user-images.githubusercontent.com/6077149/63775318-20d44800-c8f0-11e9-9196-dde762f0d816.png">

**Comment by dtsaryov** [comment]
Chart controls overlap layout because `visibility: hidden` doesn't work for `<g/>` SVG elements

**Comment by dtsaryov** [comment]
Will be fixed in cuba-platform/cuba#2410
