### ISSUE TITLE
The graph's alphaField attribute is ignored by GanttChart

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#89]
### Description of the bug or enhancement

- Minimal reproducible example

1. Define the `alphaField` attribute for a GanttChart's graph element.
2. Add an **alpha** attribute to the Segment entity
3. The other GanttChart setting on your choice.

[gantt-alpha.zip](https://github.com/cuba-platform/charts/files/3863800/gantt-alpha.zip)

- Expected behavior

The `alphaField` value is applied.

![Screenshot 2019-11-19 at 16 38 46](https://user-images.githubusercontent.com/6077149/69147494-839e3f80-0aeb-11ea-9301-429032f00e80.png)

- Actual behavior

The `alphaField` value is ignored.

![Screenshot 2019-11-19 at 16 40 46](https://user-images.githubusercontent.com/6077149/69147501-87ca5d00-0aeb-11ea-979d-2bfcfae0634a.png)

**Comment by haulmont-git** [comment]
Git changesets by `gorelov`: 

[fc248cb8](https://git.haulmont.com/platform/charts/commit/fc248cb8355f5a542d6eb7078bd7100023fadeda) in **release_6_10** - The graph's alphaField attribute is ignored by GanttChart #89
