### ISSUE TITLE
Add description to ShowPivotAction for Studio 

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/charts#91]
### Environment

- Platform version: 7.2 

### Description of the bug or enhancement
com.haulmont.charts.gui.components.action.list.ShowPivotAction
needs com.haulmont.cuba.gui.meta.StudioAction annotation with description.

Description will be shown after https://youtrack.cuba-platform.com/issue/STUDIO-7571 is implemented.

Also can think about extracting some parameters and lambdas, it it makes sense:
https://github.com/cuba-platform/cuba/issues/2412

**Comment by Flaurite** [comment]
### Changes
Added `StudioAction` and supported two properties with `StudioPropertiesItem` annotation.

New API in `com.haulmont.charts.gui.components.action.list.ShowPivotAction`:
- void setExcludedProperties(String) // excluded properties separated by comma
String getExcludedProperties()
List<String\> getExcludedPropertiesList() // returns parsed excluded properties list

- void setIncludedProperties(String) // included properties separated by comma
String getIncludedProperties()
List<String\> getIncludedPropertiesList() // returns parsed included properties list

This API is designed especially for using form XML. Examples:
```
<action id="showPivot" type="pivot_showPivot">
    <properties>
        <property name="includedProperties" value="name, value"/>
    </properties>
</action>
```
```
<action id="showPivot" type="pivot_showPivot">
    <properties>
        <property name="excludedProperties" value="description"/>
    </properties>
</action>
```
### For QA
1. Check new API from XML:
- for includedProperties
- for excludedProperties
