### ISSUE TITLE
Add missed chart listeners

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/charts#92]
### Description of the bug or enhancement

Our charts miss several listeners, e.g. `rollOverGraphItem`, `rollOutGraphItem` (https://www.amcharts.com/docs/v3/reference/amcoordinatechart/#rollOverGraphItem_event)

ToDo

1. Find out missing listeners
2. Implement
3. Add ability to define JS implementation (see an example requirement in the forum topic)

---

See: https://www.cuba-platform.com/discuss/t/ganttchart-with-rollover-effect/11128

### Solution
The Coordinate Charts (GanttChart, RadarChart, XYChart, SerialChart) has new listeners:
* **RollOutGraphListener**
The RollOutGraphListener is added to the graph. Called when the user rolls-out of a graph.
**RollOutGraphEvent** has two fields: source (chart) and graph. [Original event](https://www.amcharts.com/docs/v3/reference/amcoordinatechart/#rollOutGraph%20_event).

* **RollOutGraphItemListener**
The RollOutGraphItemListener is added to the graph item. Called when the user rolls-out of the data item.
**RollOutGraphItemEvent** has four fields: source (chart), graph, dataItem and item index. [Original event](https://www.amcharts.com/docs/v3/reference/amcoordinatechart/#rollOutGraphItem_event).

* **RollOverGraphListener**
The RollOverGraphListener is added to the graph. Called when the user rolls-over a graph.
**RollOverGraphEvent** has two fields: source (chart) and graph. [Original event](https://www.amcharts.com/docs/v3/reference/amcoordinatechart/#rollOverGraph%20_event).

* **RollOverGraphItemListener**
The RollOutGraphItemListener is added to the graph. Called when the user rolls-over data item.
**RollOutGraphItemEvent** has four fields: source (chart), graph, dataItem and item index. [Original event](https://www.amcharts.com/docs/v3/reference/amcoordinatechart/#rollOverGraphItem_event).

#### Test project
[coordinate-chart-listener.zip](https://github.com/cuba-platform/charts/files/4190273/coordinate-chart-listener.zip)

### QA
Check the work of the above listeners for Coordinate Charts (GanttChart, RadarChart, XYChart, SerialChart).

**Comment by jreznot** [comment]
By the way, It is dangerous to add those listeners since they will generate a lot of server requests.

**Comment by Mihail063** [comment]
1. Create a new entity with browser and editor screen
2. Create a new blank screen 
3. Add a new chart to the screen (one chart of the GanttChart, RadarChart, XYChart, SerialChart) for the created entity
4. Add RollOverGraphItemEvent и RollOverGraphEvent 
5. Run the project and create a new instance for the entity
6. Open the blank screen
7. Check work RollOverGraphItemListener and RollOverGraphListener

AR: 
![изображение](https://user-images.githubusercontent.com/24281695/74233645-84a6cd80-4ce4-11ea-9fe1-2d05d09d45c6.png)
